# Generated by Django 4.2.4 on 2023-12-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
